# Generated by Django 6.0.5 on 2026-06-06 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_project_project_features_project_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='tech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='app.techcategory'),
        ),
    ]
